### ISSUE TITLE
搭配稀客套餐时，当次会话下的已保存套餐仍保持响应

### ISSUE THREAD

**Issue by AnYiEE** [utaware/touhou-mystia-izakaya-web#1]
复现步骤：
1. 进入"顾客"页面
2. 在”顾客“选项卡，选择”莉格露“
3. 在”料理“选项卡，选择”海鲜味增汤“
4. 在”酒水“选项卡，选择”绿茶“
5. 料理需求选择”甜“，酒水需求选择”低酒精“
6. 保存当前套餐
7. 在”食材“选项卡，选择”蜂蜜“，点击以添加
8. _可见已保存的套餐中亦同时出现蜂蜜_
9. 保存当前套餐
10. 在”食材“选项卡，选择另一食材并添加
11. _可见当前会话下所有已保存的套餐中均出现此食材_
12. 刷新页面，重复步骤2-7
13. _可见之前保存的套餐不受影响_

**Comment by utaware** [comment]
工作之外的第一个bug，非常感谢你的反馈！已经修改并更新
